language: rust
cache:
  directories:
    - $HOME/kcov-i686-unknown-linux-gnu
    - $HOME/kcov-x86_64-unknown-linux-gnu
    - $HOME/android/android-sdk-linux
    - $HOME/android/android-18-arm-linux-androideabi-4.8
matrix:
  fast_finish: true
  include:
    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc CXX_X=aarch64-linux-gnu-g++ MODE_X=DEBUG KCOV=0
      rust: stable
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-aarch64-linux-gnu
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc CXX_X=aarch64-linux-gnu-g++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-aarch64-linux-gnu
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc CXX_X=aarch64-linux-gnu-g++ MODE_X=DEBUG KCOV=0
      rust: nightly
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-aarch64-linux-gnu
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc CXX_X=aarch64-linux-gnu-g++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-aarch64-linux-gnu
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc CXX_X=arm-linux-gnueabihf-g++ MODE_X=DEBUG KCOV=0
      rust: stable
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc CXX_X=arm-linux-gnueabihf-g++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc CXX_X=arm-linux-gnueabihf-g++ MODE_X=DEBUG KCOV=0
      rust: nightly
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc CXX_X=arm-linux-gnueabihf-g++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - g++-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross

    - env: TARGET_X=arm-linux-androideabi CC_X=arm-linux-androideabi-gcc CXX_X=arm-linux-androideabi-g++ MODE_X=DEBUG KCOV=0
      rust: stable
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless

    - env: TARGET_X=arm-linux-androideabi CC_X=arm-linux-androideabi-gcc CXX_X=arm-linux-androideabi-g++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless

    - env: TARGET_X=arm-linux-androideabi CC_X=arm-linux-androideabi-gcc CXX_X=arm-linux-androideabi-g++ MODE_X=DEBUG KCOV=0
      rust: nightly
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless

    - env: TARGET_X=arm-linux-androideabi CC_X=arm-linux-androideabi-gcc CXX_X=arm-linux-androideabi-g++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      addons:
        apt:
          packages:
            - expect
            - openjdk-6-jre-headless

    # The lines from "# BEGIN GENERATED" through "# END GENERATED" are
    # generated by running |python mk/update-travis-yml.py|. Any changes
    # made to those lines will be overwritten while other lines will be left
    # untouched.
    #
    # BEGIN GENERATED

    - env: TARGET_X=x86_64-apple-darwin CC_X=clang CXX_X=clang++ MODE_X=DEBUG KCOV=0
      rust: stable
      os: osx
      osx_image: xcode7.2

    - env: TARGET_X=x86_64-apple-darwin CC_X=clang CXX_X=clang++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: osx
      osx_image: xcode7.2

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - gcc-multilib
            - libc6-dev-i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - gcc-multilib
            - libc6-dev-i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-5
            - gcc-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-5
            - gcc-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=DEBUG KCOV=0
      rust: stable
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=RELWITHDEBINFO KCOV=0
      rust: stable
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-apple-darwin CC_X=clang CXX_X=clang++ MODE_X=DEBUG KCOV=0
      rust: nightly
      os: osx
      osx_image: xcode7.2

    - env: TARGET_X=x86_64-apple-darwin CC_X=clang CXX_X=clang++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      os: osx
      osx_image: xcode7.2

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=DEBUG KCOV=0
      rust: nightly
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - gcc-multilib
            - libc6-dev-i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - gcc-multilib
            - libc6-dev-i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=DEBUG KCOV=0
      rust: nightly
      os: linux

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      os: linux

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=DEBUG KCOV=1
      rust: nightly
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-5
            - gcc-5-multilib
            - libcurl3:i386
            - libcurl4-openssl-dev:i386
            - libdw-dev:i386
            - libelf-dev:i386
            - libkrb5-dev:i386
            - libssl-dev:i386
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-5
            - gcc-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=DEBUG KCOV=1
      rust: nightly
      os: linux
      addons:
        apt:
          packages:
            - binutils-dev
            - g++-5
            - gcc-5
            - libcurl4-openssl-dev
            - libdw-dev
            - libelf-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=RELWITHDEBINFO KCOV=0
      rust: nightly
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-apple-darwin CC_X=clang CXX_X=clang++ MODE_X=DEBUG KCOV=0
      rust: beta
      os: osx
      osx_image: xcode7.2

    - env: TARGET_X=x86_64-apple-darwin CC_X=clang CXX_X=clang++ MODE_X=RELWITHDEBINFO KCOV=0
      rust: beta
      os: osx
      osx_image: xcode7.2

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=DEBUG KCOV=0
      rust: beta
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - gcc-multilib
            - libc6-dev-i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=RELWITHDEBINFO KCOV=0
      rust: beta
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - gcc-multilib
            - libc6-dev-i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=DEBUG KCOV=0
      rust: beta
      os: linux

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-4.6 CXX_X=g++-4.6 MODE_X=RELWITHDEBINFO KCOV=0
      rust: beta
      os: linux

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=DEBUG KCOV=0
      rust: beta
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-5
            - gcc-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=RELWITHDEBINFO KCOV=0
      rust: beta
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - g++-5-multilib
            - gcc-5
            - gcc-5-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=DEBUG KCOV=0
      rust: beta
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-5 CXX_X=g++-5 MODE_X=RELWITHDEBINFO KCOV=0
      rust: beta
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

    # END GENERATED

script: if [[ "$TARGET_X" =~ ^a*.*linux-.*eabi ]]; then travis_wait 60 mk/travis.sh; else mk/travis.sh; fi
