language: rust
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: linux
      dist: focal
      install: rustup component add rustfmt
      script: cargo fmt -- --check

    # Verify that we build on Trusty, which has GCC 4.8 as the default GCC
    # version. GCC 4.8 is the minimum version of GCC we support.

    - env: TARGET_X=x86_64-unknown-linux-gnu FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      dist: trusty

    - env: TARGET_X=x86_64-unknown-linux-gnu FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      dist: trusty

    - env: TARGET_X=i686-unknown-linux-gnu  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - gcc-multilib
            - libc6-dev-i386

    # Verify that we build with GCC 9, the default compiler on Focal.

    - env: TARGET_X=x86_64-unknown-linux-gnu  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal

    - env: TARGET_X=x86_64-unknown-linux-gnu  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal

    - env: TARGET_X=i686-unknown-linux-gnu  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - gcc-multilib
            - libc6-dev-i386

    # The lines from "# BEGIN GENERATED" through "# END GENERATED" are
    # generated by running |python mk/update-travis-yml.py|. Any changes
    # made to those lines will be overwritten while other lines will be left
    # untouched.
    #
    # BEGIN GENERATED

    - env: TARGET_X=aarch64-apple-ios  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: osx
      osx_image: xcode12

    - env: TARGET_X=aarch64-apple-ios  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: osx
      osx_image: xcode12

    - env: TARGET_X=x86_64-apple-darwin  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: osx
      osx_image: xcode12

    - env: TARGET_X=x86_64-apple-darwin  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: osx
      osx_image: xcode12

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android21-clang FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      language: android
      android:
        components:
        - android-21
        - build-tools-26.0.2
      dist: trusty

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android21-clang FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      language: android
      android:
        components:
        - android-21
        - build-tools-26.0.2
      dist: trusty

    - env: TARGET_X=armv7-linux-androideabi CC_X=armv7a-linux-androideabi18-clang FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      language: android
      android:
        components:
        - android-18
        - build-tools-26.0.2
        - sys-img-armeabi-v7a-android-18
      dist: trusty

    - env: TARGET_X=armv7-linux-androideabi CC_X=armv7a-linux-androideabi18-clang FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      language: android
      android:
        components:
        - android-18
        - build-tools-26.0.2
        - sys-img-armeabi-v7a-android-18
      dist: trusty

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user-binfmt

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user-binfmt

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user-binfmt

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable
      rust: stable
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user-binfmt

    - env: TARGET_X=aarch64-apple-ios  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: osx
      osx_image: xcode12

    - env: TARGET_X=aarch64-apple-ios  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: osx
      osx_image: xcode12

    - env: TARGET_X=x86_64-apple-darwin  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: osx
      osx_image: xcode12

    - env: TARGET_X=x86_64-apple-darwin  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: osx
      osx_image: xcode12

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android21-clang FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      language: android
      android:
        components:
        - android-21
        - build-tools-26.0.2
      dist: trusty

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android21-clang FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      language: android
      android:
        components:
        - android-21
        - build-tools-26.0.2
      dist: trusty

    - env: TARGET_X=armv7-linux-androideabi CC_X=armv7a-linux-androideabi18-clang FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      language: android
      android:
        components:
        - android-18
        - build-tools-26.0.2
        - sys-img-armeabi-v7a-android-18
      dist: trusty

    - env: TARGET_X=armv7-linux-androideabi CC_X=armv7a-linux-androideabi18-clang FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      language: android
      android:
        components:
        - android-18
        - build-tools-26.0.2
        - sys-img-armeabi-v7a-android-18
      dist: trusty

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=1 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - kcov

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user-binfmt

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user-binfmt

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=1 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - kcov
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user-binfmt

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=nightly
      rust: nightly
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user-binfmt

    - env: TARGET_X=aarch64-apple-ios  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: osx
      osx_image: xcode12

    - env: TARGET_X=aarch64-apple-ios  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: osx
      osx_image: xcode12

    - env: TARGET_X=x86_64-apple-darwin  FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: osx
      osx_image: xcode12

    - env: TARGET_X=x86_64-apple-darwin  FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: osx
      osx_image: xcode12

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android21-clang FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      language: android
      android:
        components:
        - android-21
        - build-tools-26.0.2
      dist: trusty

    - env: TARGET_X=aarch64-linux-android CC_X=aarch64-linux-android21-clang FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      language: android
      android:
        components:
        - android-21
        - build-tools-26.0.2
      dist: trusty

    - env: TARGET_X=armv7-linux-androideabi CC_X=armv7a-linux-androideabi18-clang FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      language: android
      android:
        components:
        - android-18
        - build-tools-26.0.2
        - sys-img-armeabi-v7a-android-18
      dist: trusty

    - env: TARGET_X=armv7-linux-androideabi CC_X=armv7a-linux-androideabi18-clang FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      language: android
      android:
        components:
        - android-18
        - build-tools-26.0.2
        - sys-img-armeabi-v7a-android-18
      dist: trusty

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=x86_64-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user-binfmt

    - env: TARGET_X=aarch64-unknown-linux-gnu CC_X=aarch64-linux-gnu-gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
            - qemu-user-binfmt

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=i686-unknown-linux-musl CC_X=clang-10 FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - clang-10
            - gcc-multilib
            - libc6-dev-i386

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user-binfmt

    - env: TARGET_X=arm-unknown-linux-gnueabihf CC_X=arm-linux-gnueabihf-gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=beta
      rust: beta
      os: linux
      dist: focal
      addons:
        apt:
          packages:
            - binfmt-support
            - gcc-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - qemu-user-binfmt

    # END GENERATED

install: mk/install-build-tools.sh
script: if [[ "$TARGET_X" =~ ^a*.*linux-.* && "$MODE_X" == "RELWITHDEBINFO" ]]; then travis_wait 60 mk/travis.sh; else mk/travis.sh; fi
